baseURL = 'https://leas.ee/'
languageCode = 'en-us'
title = 'Leas'
theme = 'blist'

[params]
  darkModeToggle = true

[[menu.main]]
  name = "Blogi"
  url = "/blog"

[[menu.main]]
  name = "Kuhu minna"
  url = "/kuhuminna"